version: '3.8'

services:
  fastapi-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data     
      - ./backend/logs:/app/logs      
    ports:
      - "${BACKEND_PORT}:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network
    restart: unless-stopped

  streamlit-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    env_file:
      - .env
    depends_on:
      - fastapi-backend
    volumes:
      - ./frontend:/app          
    ports:
      - "${FRONTEND_PORT}:8501"
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
